### ISSUE TITLE
Under webpack, Actions is undefined, Constants is undefined on import

### ISSUE THREAD

**Issue by fairbairn** [grigory-leonenko/redux-easy-actions#3]
Not sure if something has changed from your earliest README, but when run from webpack, following your guideline, and attempting to do this...

```
import { Actions } from 'Actions';
```

or

```
import { Constants } from 'Actions';
```

it fails, with a JS error as such..

```
TypeError: _Actions.Actions is undefined
```

The solution, although strange, was to do this on our side...

```
import actions from 'Actions';
const { Actions } = actions;
```

Our assumption is that the babel compiler tries to resolve sooner, and thus doesn't find the exports, but at runtime, it can pull it out of the exported dictionary.

**Comment by grigory-leonenko** [comment]
As far as I know desctructing in import from object exported as default not supported by babel, because standartd doesn't support this as well. Thanks for the comment, I will correct it in the documentation. I offer such a solution:

``` js
const {Actions, Constants} = EasyActions(User, Notifications);

export {Actions as Actions}
export {Constants as Constants}
```
